#!/bin/bash
# Single source of truth: the exact contents of every file this configuration
# installs. install.sh writes them, verify.sh compares against them and
# uninstall.sh removes them. Nothing else should ever restate these contents.
#
# Two further files are machine-specific (root filesystem UUID and the swap
# file's physical offset) and are generated by install.sh instead.

FILES=(
  "/usr/lib/systemd/system-sleep/50-wifi-reset|0755|f_usr_lib_systemd_system_sleep_50_wifi_reset"
  "/usr/lib/systemd/system-sleep/99-battery-log|0755|f_usr_lib_systemd_system_sleep_99_battery_log"
  "/etc/systemd/sleep.conf.d/99-hibernate.conf|0644|f_etc_systemd_sleep_conf_d_99_hibernate_conf"
  "/etc/systemd/logind.conf.d/99-lid.conf|0644|f_etc_systemd_logind_conf_d_99_lid_conf"
  "/etc/dconf/db/local.d/00-macbook-sleep|0644|f_etc_dconf_db_local_d_00_macbook_sleep"
  "/etc/dconf/db/local.d/locks/macbook-sleep|0644|f_etc_dconf_db_local_d_locks_macbook_sleep"
  "/etc/systemd/logind.conf.d/99-idle.conf|0644|f_etc_systemd_logind_conf_d_99_idle_conf"
  "/usr/local/sbin/disable-wake-sources|0755|f_usr_local_sbin_disable_wake_sources"
  "/etc/systemd/system/disable-wake-sources.service|0644|f_etc_systemd_system_disable_wake_sources_service"
  "/usr/local/sbin/wifi-recover|0755|f_usr_local_sbin_wifi_recover"
  "/etc/systemd/system/wifi-recover.service|0644|f_etc_systemd_system_wifi_recover_service"
  "/etc/systemd/system/wifi-recover.timer|0644|f_etc_systemd_system_wifi_recover_timer"
  "/usr/local/sbin/sleep-check|0755|f_usr_local_sbin_sleep_check"
  "/usr/local/bin/sleep-power|0755|f_usr_local_bin_sleep_power"
  "/etc/apt/apt.conf.d/99-macbook-sleep-check|0644|f_etc_apt_apt_conf_d_99_macbook_sleep_check"
  "/usr/local/sbin/sleep-probe|0755|f_usr_local_sbin_sleep_probe"
)

f_usr_lib_systemd_system_sleep_50_wifi_reset() { cat <<'FILE_EOF'
#!/bin/sh
# Broadcom BCM4350 firmware hangs after some hours of uptime and stops
# answering the D3 request, which aborts every suspend. Unload the driver
# before sleep, load it back on resume, force a PCI rescan if it is missing.
LOG=/var/log/macbook-sleep-wifi.log
IFACE=wlp2s0
PCI=0000:02:00.0
stamp() { date '+%F %T'; }
# Re-binding the driver re-arms ARPT as a wake source, which lets the card
# power the machine on from hibernation. Re-apply the wake policy every time.
wake_off() { [ -x /usr/local/sbin/disable-wake-sources ] && /usr/local/sbin/disable-wake-sources >/dev/null 2>&1; }
case "$1" in
  pre)
    i=1
    while [ $i -le 3 ]; do
      if /usr/sbin/modprobe -r brcmfmac_wcc brcmfmac 2>>"$LOG"; then
        wake_off
        echo "$(stamp) pre: driver unloaded (attempt $i)" >> "$LOG"
        exit 0
      fi
      sleep 2
      i=$((i+1))
    done
    wake_off
    echo "$(stamp) pre: FAILED to unload driver after 3 attempts" >> "$LOG"
    ;;
  post)
    /usr/sbin/modprobe brcmfmac 2>>"$LOG"
    sleep 3
    if /usr/sbin/ip link show "$IFACE" >/dev/null 2>&1; then
      echo "$(stamp) post: driver loaded" >> "$LOG"
    else
      echo "$(stamp) post: interface missing, forcing PCI rescan" >> "$LOG"
      /usr/sbin/modprobe -r brcmfmac_wcc brcmfmac 2>>"$LOG"
      [ -e "/sys/bus/pci/devices/$PCI/remove" ] && echo 1 > "/sys/bus/pci/devices/$PCI/remove"
      sleep 2
      echo 1 > /sys/bus/pci/rescan
      sleep 3
      /usr/sbin/modprobe brcmfmac 2>>"$LOG"
      sleep 3
      if /usr/sbin/ip link show "$IFACE" >/dev/null 2>&1; then
        echo "$(stamp) post: recovered by PCI rescan" >> "$LOG"
      else
        echo "$(stamp) post: RECOVERY FAILED" >> "$LOG"
      fi
    fi
    wake_off
    ;;
esac
FILE_EOF
}

f_usr_lib_systemd_system_sleep_99_battery_log() { cat <<'FILE_EOF'
#!/bin/sh
# Records charge level and energy before and after every sleep operation,
# so power draw can be measured afterwards. AC adapter on this Mac is ADP1.
B=/sys/class/power_supply/BAT0
AC=$(cat /sys/class/power_supply/ADP1/online 2>/dev/null || echo "?")
echo "$(date '+%F %T') $1 $2 level=$(cat $B/capacity)% energy=$(cat $B/energy_now 2>/dev/null || cat $B/charge_now 2>/dev/null) ac=$AC" >> /var/log/macbook-sleep-battery.log
FILE_EOF
}

f_etc_systemd_sleep_conf_d_99_hibernate_conf() { cat <<'FILE_EOF'
# Move from suspend to hibernation after one hour on battery.
# s2idle never reaches S0ix on this machine and costs about 6 %/h,
# hibernation costs about 0.5 %/h.
[Sleep]
HibernateDelaySec=60min
FILE_EOF
}

f_etc_systemd_logind_conf_d_99_lid_conf() { cat <<'FILE_EOF'
# Closing the lid on battery suspends first, then hibernates
# after the delay set in 99-hibernate.conf.
# On AC power plain suspend is enough.
[Login]
HandleLidSwitch=suspend-then-hibernate
HandleLidSwitchExternalPower=suspend
FILE_EOF
}

f_etc_dconf_db_local_d_00_macbook_sleep() { cat <<'FILE_EOF'
# Idling must never suspend this machine (see 99-idle.conf).
# Screen blanking and locking stay untouched; only sleeping is taken away.
[org/gnome/settings-daemon/plugins/power]
sleep-inactive-battery-type='nothing'
sleep-inactive-ac-type='nothing'
FILE_EOF
}

f_etc_dconf_db_local_d_locks_macbook_sleep() { cat <<'FILE_EOF'
/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type
/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
FILE_EOF
}

f_etc_systemd_logind_conf_d_99_idle_conf() { cat <<'FILE_EOF'
# Idling must never put this machine to sleep: an idle-triggered suspend
# hung it once, while lid-triggered suspends kept working. The screen still
# blanks and locks through GNOME; only sleeping is taken away.
[Login]
IdleAction=ignore
FILE_EOF
}

f_usr_local_sbin_disable_wake_sources() { cat <<'FILE_EOF'
#!/bin/sh
# Apple firmware lets the lid sensor (LID0) and the Wi-Fi card (ARPT) power the
# machine on from S4. The lid reports spurious events, so the laptop wakes itself
# minutes after hibernating, with no trace in any system log.
# Writing a device name to /proc/acpi/wakeup TOGGLES it, so check state first.
for dev in ARPT LID0; do
  if grep -q "^$dev.*\*enabled" /proc/acpi/wakeup; then
    echo "$dev" > /proc/acpi/wakeup
  fi
done
exit 0
FILE_EOF
}

f_etc_systemd_system_disable_wake_sources_service() { cat <<'FILE_EOF'
[Unit]
Description=Revoke lid and Wi-Fi permission to wake the machine from hibernation
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/disable-wake-sources

[Install]
WantedBy=multi-user.target
FILE_EOF
}

f_usr_local_sbin_wifi_recover() { cat <<'FILE_EOF'
#!/bin/sh
# A warm reboot does not power-cycle the Broadcom chip, so the driver sometimes
# reads 0xffffffff instead of the chip id and the interface never appears.
# Making the bus re-enumerate the device brings it back. Does nothing when the
# interface is already there.
IFACE=wlp2s0
PCI=0000:02:00.0
/usr/sbin/ip link show "$IFACE" >/dev/null 2>&1 && exit 0
logger "wifi-recover: $IFACE missing, forcing PCI rescan"
/usr/sbin/modprobe -r brcmfmac_wcc brcmfmac 2>/dev/null
[ -e "/sys/bus/pci/devices/$PCI/remove" ] && echo 1 > "/sys/bus/pci/devices/$PCI/remove"
sleep 2
echo 1 > /sys/bus/pci/rescan
sleep 3
/usr/sbin/modprobe brcmfmac 2>/dev/null
sleep 3
if /usr/sbin/ip link show "$IFACE" >/dev/null 2>&1; then
  logger "wifi-recover: $IFACE recovered"
else
  logger "wifi-recover: recovery failed"
fi
exit 0
FILE_EOF
}

f_etc_systemd_system_wifi_recover_service() { cat <<'FILE_EOF'
[Unit]
Description=Bring back the Wi-Fi interface if it did not appear after boot

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/wifi-recover
FILE_EOF
}

f_etc_systemd_system_wifi_recover_timer() { cat <<'FILE_EOF'
[Unit]
Description=Check the Wi-Fi interface 25 seconds after boot

[Timer]
OnBootSec=25s
AccuracySec=1s

[Install]
WantedBy=timers.target
FILE_EOF
}

f_usr_local_sbin_sleep_check() { cat <<'FILE_EOF'
#!/bin/bash
# Verifies every piece of the MacBook sleep/hibernate configuration.
# Run it after kernel or systemd updates:  sudo sleep-check
t() { if eval "$2" >/dev/null 2>&1; then echo "  OK      $1"; else echo "  MISSING $1"; fi; }
echo "=== MacBook sleep configuration ==="
t "kernel parameter pcie_port_pm=off" 'grep -q pcie_port_pm=off /proc/cmdline'
t "kernel parameter resume"           'grep -q resume=UUID /proc/cmdline'
t "initramfs resume config"           '[ -f /etc/initramfs-tools/conf.d/resume ]'
t "sleep mode s2idle"                 'grep -q "\[s2idle\]" /sys/power/mem_sleep'
t "swap file at least 16 GB"          '[ $(swapon --show=SIZE --bytes --noheadings | head -1) -ge 17000000000 ]'
t "resume_offset matches swap file"   '[ "$(grep -o "resume_offset=[0-9]*" /proc/cmdline | cut -d= -f2)" = "$(filefrag -v /swap.img | awk "\$1==\"0:\"{print \$4}" | tr -d .)" ]'
t "wifi reset sleep hook"             '[ -x /usr/lib/systemd/system-sleep/50-wifi-reset ]'
t "battery logging sleep hook"        '[ -x /usr/lib/systemd/system-sleep/99-battery-log ]'
t "hibernate delay config"            '[ -f /etc/systemd/sleep.conf.d/99-hibernate.conf ]'
t "lid set to suspend-then-hibernate" 'busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager HandleLidSwitch | grep -q suspend-then-hibernate'
t "disable-wake-sources service"      'systemctl is-enabled disable-wake-sources.service'
t "wifi-recover timer"                'systemctl is-enabled wifi-recover.timer'
t "lid cannot wake from hibernation"  'grep -q "^LID0.*\*disabled" /proc/acpi/wakeup'
t "wifi cannot wake from hibernation" 'grep -q "^ARPT.*\*disabled" /proc/acpi/wakeup'
t "idle leaves the machine running"     'busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager IdleAction | grep -q ignore'
t "GNOME never suspends on idle"        'sudo -u ${SUDO_USER:-$USER} DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u ${SUDO_USER:-$USER})/bus gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type | grep -q nothing'
t "no dead hooks in /etc"             '[ ! -d /etc/systemd/system-sleep ]'
t "that setting is locked"            '[ -f /etc/dconf/db/local.d/locks/macbook-sleep ]'
FILE_EOF
}

f_usr_local_bin_sleep_power() { cat <<'FILE_EOF'
#!/bin/bash
# Reports battery drain for every sleep longer than 10 minutes, on battery only.
# Source: /var/log/macbook-sleep-battery.log written by the 99-battery-log hook.
# Accepts both the current field names and the older ones.
LOG=/var/log/macbook-sleep-battery.log
FULL=$(cat /sys/class/power_supply/BAT0/energy_full 2>/dev/null || cat /sys/class/power_supply/BAT0/charge_full 2>/dev/null)
printf "%-20s %10s %12s\n" "SLEEP STARTED" "LENGTH" "DRAIN"
while read -r d tm phase rest; do
  e=$(echo "$rest" | grep -oE '(energy|energia)=[0-9]+' | cut -d= -f2)
  a=$(echo "$rest" | grep -oE '(ac|zasilacz)=[^ ]+' | cut -d= -f2)
  [ -z "$e" ] && continue
  if [ "$phase" = "pre" ]; then
    pre_ts=$(date -d "$d $tm" +%s); pre_e=$e; pre_a=$a; pre_h="$d $tm"
  elif [ "$phase" = "post" ] && [ -n "$pre_ts" ]; then
    ts=$(date -d "$d $tm" +%s); dt=$((ts-pre_ts)); pre_ts=""
    [ "$dt" -lt 600 ] && continue
    if [ "$pre_a" != "0" ] || [ "$a" != "0" ]; then
      printf "%-20s %6d min %12s\n" "$pre_h" $((dt/60)) "on AC"; continue
    fi
    pct=$(awk -v x=$((pre_e-e)) -v f=$FULL -v s=$dt 'BEGIN{ if(f>0) printf "%.2f %%/h", (x/f)*100/(s/3600); else print "?" }')
    printf "%-20s %6d min %12s\n" "$pre_h" $((dt/60)) "$pct"
  fi
done < "$LOG"
FILE_EOF
}

f_etc_apt_apt_conf_d_99_macbook_sleep_check() { cat <<'FILE_EOF'
// After every package operation, record the state of the sleep configuration.
// Read-only: it reports, it never changes anything. Never fails the apt run.
// Log: /var/log/macbook-sleep-check.log
DPkg::Post-Invoke { "{ echo; date '+=== %F %T ==='; SUDO_USER=$(loginctl list-users --no-legend | awk '$1>=1000{print $2; exit}') /usr/local/sbin/sleep-check; } >> /var/log/macbook-sleep-check.log 2>&1 || true"; };
FILE_EOF
}

f_usr_local_sbin_sleep_probe() { cat <<'FILE_EOF'
#!/bin/bash
# Diagnostic run: suspends for 60 s, then reports how long it actually slept,
# whether the disk survived, and which interrupts and ACPI events fired.
# Use this when sleep starts misbehaving again.
#
# NOTE: rtcwake writes straight to the kernel and BYPASSES systemd, so the
# hooks in /usr/lib/systemd/system-sleep are NOT run by this test. To exercise
# those, use:  rtcwake -m no -s 60 && systemctl suspend -i
cp /proc/interrupts /dev/shm/irq_before
grep -H . /sys/firmware/acpi/interrupts/* > /dev/shm/gpe_before 2>/dev/null
T0=$(date +%s)
rtcwake -m mem -s 60
T1=$(date +%s)
sleep 3
cp /proc/interrupts /dev/shm/irq_after
grep -H . /sys/firmware/acpi/interrupts/* > /dev/shm/gpe_after 2>/dev/null
echo "=== SLEPT: $((T1-T0)) s (expected 60) ==="
if dd if=/dev/nvme0n1 of=/dev/null bs=4k count=1 iflag=direct 2>/dev/null; then
  echo "=== DISK: OK ==="
else
  echo "=== DISK: GONE ==="
fi
echo "=== INTERRUPT DELTAS ==="
awk 'NR==FNR{s=0;for(i=2;i<=NF;i++) if($i+0==$i) s+=$i; a[$1]=s; next} {s=0;n="";for(i=2;i<=NF;i++){if($i+0==$i) s+=$i; else n=n" "$i} d=s-a[$1]; if(d>0) printf "%-8s +%-8d%s\n",$1,d,n}' /dev/shm/irq_before /dev/shm/irq_after
echo "=== ACPI EVENT DELTAS ==="
awk -F: 'NR==FNR{split($2,f," "); a[$1]=f[1]; next} {split($2,f," "); d=f[1]-a[$1]; if(d>0) print $1, "+"d}' /dev/shm/gpe_before /dev/shm/gpe_after
echo "=== SUSPEND ERRORS ==="
dmesg | grep -iE 'failed to suspend|aborted|Identify Controller|I/O error|enter_D3' | tail -10
rm -f /dev/shm/irq_before /dev/shm/irq_after /dev/shm/gpe_before /dev/shm/gpe_after
FILE_EOF
}
